/*
 *  Copyright 2010 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) microsoft.targets; 1, 0, 2, 0,431; 12-7-2010 14:48:06; /db/ztree/library/trees/xdctargets/xdctargets-c37x/src/ xlibrary

 */

