/*
 *  Copyright 2010 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) gnu.targets; 1, 0, 1,431; 12-7-2010 14:48:08; /db/ztree/library/trees/xdctargets/xdctargets-c37x/src/ xlibrary

 */

