/*
 *  Copyright 2010 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) ti.targets; 1, 0, 3,429; 12-7-2010 14:48:18; /db/ztree/library/trees/xdctargets/xdctargets-c37x/src/ xlibrary

 */

