/*
 *  Copyright 2010 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) ti.targets.elf; 1, 0, 0,196; 12-7-2010 14:48:23; /db/ztree/library/trees/xdctargets/xdctargets-c37x/src/ xlibrary

 */

